Traceback (most recent call last):
  File "/home/sie/miniconda3/envs/env1/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/sie/miniconda3/envs/env1/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sie/miniconda3/envs/env1/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sie/miniconda3/envs/env1/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/sie/miniconda3/envs/env1/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/sie/miniconda3/envs/env1/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/sie/miniconda3/envs/env1/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Show random images
dirpath = '/content/drive/MyDrive/Colab Notebooks/10_food_classes_10_percent/train/'
classname = 'ramen/'

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import random

files = os.listdir(dirpath + classname)
img = mpimg.imread(dirpath+classname+random.choice(files))

plt.imshow(img)
plt.axis('off')
plt.show();
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[4], line 9[0m
[1;32m      6[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mimage[39;00m [38;5;28;01mas[39;00m [38;5;21;01mmpimg[39;00m
[1;32m      7[0m [38;5;28;01mimport[39;00m [38;5;21;01mrandom[39;00m
[0;32m----> 9[0m files [38;5;241m=[39m os[38;5;241m.[39mlistdir(dirpath [38;5;241m+[39m classname)
[1;32m     10[0m img [38;5;241m=[39m mpimg[38;5;241m.[39mimread(dirpath[38;5;241m+[39mclassname[38;5;241m+[39mrandom[38;5;241m.[39mchoice(files))
[1;32m     12[0m plt[38;5;241m.[39mimshow(img)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/content/drive/MyDrive/Colab Notebooks/10_food_classes_10_percent/train/ramen/'

